### ISSUE TITLE
Solder Mask and Copper layer's are fused (KiCad 7.0.8)

### ISSUE THREAD

**Issue by hexpwn** [pcbway/PCBWay-Plug-in-for-Kicad#16]
First time using KiCad and the plugin but I believe layers are being exported incorrectly. 
In this case, the solder mask and copper layer were merged.

![issue1](https://github.com/pcbway/PCBWay-Plug-in-for-Kicad/assets/58829864/d67e75bb-7729-4d0f-b4d4-483b4cb7a3d4)
![issue2](https://github.com/pcbway/PCBWay-Plug-in-for-Kicad/assets/58829864/0c21cb66-11d6-4837-b2c8-2eff8ac4b0a1)

**Comment by hexpwn** [comment]
It seems this is actually an issue with how KiCad is importing .zip files in the gerber viewer.

**Comment by pcbway** [comment]
Thanks for the feedback.
