### ISSUE TITLE
No longer works in KiCAD version 8 release 3

### ISSUE THREAD

**Issue by Joshc17m** [pcbway/PCBWay-Plug-in-for-Kicad#17]
Does not open in PCBway site, no files are transferred, or even put into zip file. I do however get the error "FOOTPRINT object has no attribute "HasProperty". 

I thought maybe it was because I'm using the new version, but opened an old board from version 7.10 and get the same error, where I didn't get the error in previous versions.

**Comment by pcbway** [comment]
yes,the kicad8.0 night version has the problem,we are debugging it.
You could use kicad 7 first.
Regards

**Comment by pcbway** [comment]
Hi,The plug-in has been updated and can now adapt to kicad8 and kicad7 versions. You can update and use it directly. Thanks very much
