### ISSUE TITLE
BOM file generation

### ISSUE THREAD

**Issue by fit-devs** [pcbway/PCBWay-Plug-in-for-Kicad#3]
Consider generating BOM file which can be used by people responsible for assembly in pcbway.com.
They do not know how to use PCBWay_components.json.
The internal  system of pcbway.com shows them missing BOM and so they do not review the assembly order.
When I asked the to review the order they asked me for BOM open-able in excel.

**Comment by pcbway** [comment]
Hi
We get the component information and are updating the system. The sales not familiar with json data,but now this problem has beeen solved,thanks for your feedback
